### PR TITLE
changed all sampling statements NUTS()

### LINKED ISSUE #29: Incorrect `sample` statement
All of the `sample` statements are incorrect for Turing Models:

This implies that Turing will sample 2_000 iterations after discarding the `nadapts` default in `NUTS()` (which is 1_000). So this gives you 3_000 iterations with 1_000 as warmup.

```julia
sample(model, NUTS(), MCMCThreads(), 2_000, 4)
```

The correct approach would be:
```julia
sample(model, NUTS(1_000, 0.8), MCMCThreads(), 1_000, 4)
```

### PR DESCRIPTION
**Pull request by storopoli**
Closes #29.

### CODE REVIEW

File: turing/02-linear_regression-kidiq.jl [hunk 1]
```diff
@@ -29,24 +29,23 @@ y = standardize(ZScoreTransform, y; dims=1)
...
-    return(; y, α, β, σ)
+    return (; y, α, β, σ)
 end
 
 # instantiate the model
 model = linear_regression(X, y)
 
-# sample with NUTS, 4 multi-threaded parallel chains, and 2k iters
-chn = sample(model, NUTS(), MCMCThreads(), 2_000, 4)
+# sample with NUTS, 4 multi-threaded parallel chains, and 2k iters with 1k warmup with 1k warmup
```
Comment (storopoli) [inline turing/02-linear_regression-kidiq.jl:38]:
```suggestion
# sample with NUTS, 4 multi-threaded parallel chains, and 2k iters with 1k warmup
```
